In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import re
import os

In [3]:
def Read_all_csv(folder_path):
    dataframe={}
    for file in glob.glob(os.path.join(folder_path,"*.csv")):
        name = file.split("\\")[-1].replace(".csv","")
        dataframe[name]=pd.read_csv(file)
    return dataframe

In [4]:
folder_path = "D:\\DATA SETS (Project)\\Capston Project Data\\UPI_Transactions_Data_Analysis"
dfs = Read_all_csv(folder_path)
customer_feedback = dfs['customer_feedback_surveys']
customer_details = dfs['customer_master']
device_info = dfs['device_info']
fraud_alert = dfs['fraud_alert_history']
merchant = dfs['merchant_info']
account_details = dfs['upi_account_details']
transaction_history = dfs['upi_transaction_history']

In [5]:
customer_details.head()

,customer_id,full_name,mobile_number,age,gender,region,date_joined,is_business_user,risk_score
0,cust100000,Ryan Gallagher,7631706690,26,female,north,2024-01-28,False,0.39
1,cust100001,Robert Garza,806360837,49,female,west,2025-04-16,False,0.13
2,cust100002,Haley Rhodes,8124158683,68,male,west,2022-02-10,True,0.14
3,cust100003,Sonya Mathis,3662585178,42,male,north,2021-02-18,False,0.07
4,cust100004,Ryan Wood,9996228303,35,female,south,2023-04-17,False,0.30

In [6]:
customer_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10000 non-null  object
 1   full_name         10000 non-null  object
 2   mobile_number     10000 non-null  int64
 3   age               10000 non-null  int64
 4   gender            10000 non-null  object
 5   region            10000 non-null  object
 6   date_joined       10000 non-null  object
 7   is_business_user  10000 non-null  bool
 8   risk_score        10000 non-null  float64
dtypes: bool(1), float64(1), int64(2), object(5)
memory usage: 634.9+ KB

In [7]:
customer_details['date_joined'] = pd.to_datetime(customer_details['date_joined'])

In [8]:
customer_feedback.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   feedback_id         4000 non-null   object
 1   customer_id         4000 non-null   object
 2   date_submitted      4000 non-null   object
 3   feedback_text       4000 non-null   object
 4   satisfaction_score  4000 non-null   int64
 5   issue_type          4000 non-null   object
 6   resolved            4000 non-null   bool
dtypes: bool(1), int64(1), object(5)
memory usage: 191.5+ KB

In [9]:
customer_feedback.head()

,feedback_id,customer_id,date_submitted,feedback_text,satisfaction_score,issue_type,resolved
0,fdbk100000,cust106029,2021-08-14,Weight what decision able gun shoulder.,4,fraud,True
1,fdbk100001,cust101758,2025-03-30,Case discuss approach leave hair.,3,transaction,False
2,fdbk100002,cust107269,2025-07-24,Idea as effect bed need shake.,4,app_usability,False
3,fdbk100003,cust108175,2024-06-07,Image design soldier strategy character learn ...,4,app_usability,False
4,fdbk100004,cust101420,2022-01-12,Two lose traditional approach commercial throw...,3,transaction,True

In [10]:
customer_feedback['date_submitted'] = pd.to_datetime(customer_feedback['date_submitted'])

In [11]:
device_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   device_id    12000 non-null  object
 1   customer_id  12000 non-null  object
 2   device_type  12000 non-null  object
 3   app_version  12000 non-null  object
 4   is_rooted    12000 non-null  bool
 5   last_active  12000 non-null  object
dtypes: bool(1), object(5)
memory usage: 480.6+ KB

In [12]:
device_info.head()

,device_id,customer_id,device_type,app_version,is_rooted,last_active
0,dev100000,cust100000,android,2.5.4,False,2024-10-19 01:24:57.637823
1,dev100001,cust100001,feature_phone,2.6.18,False,2025-07-16 01:53:08.805876
2,dev100002,cust100002,android,2.5.0,False,2024-04-25 05:09:53.162261
3,dev100003,cust100003,android,2.4.12,False,2021-04-24 19:10:51.551382
4,dev100004,cust100004,feature_phone,4.2.0,False,2024-09-15 01:18:05.200875

In [13]:
device_info['last_active'] = pd.to_datetime(device_info['last_active'])

In [14]:
fraud_alert.head()

,alert_id,transaction_id,alert_type,alert_date,resolved,resolution_date,remarks
0,alert134117,txn10034117,frequent_failure,2025-08-03 13:29:58.950559,False,NaN,Strategy forward the risk necessary company re...
1,alert183925,txn10083925,frequent_failure,2024-10-09 09:41:15.203880,True,2024-10-11 02:41:15.203880,Art do federal short.
2,alert163439,txn10063439,unusual_time,2025-02-23 01:23:55.939700,True,2025-02-24 10:23:55.939700,Age board fine participant join.
3,alert164967,txn10064967,frequent_failure,2025-07-08 21:50:16.926780,True,2025-07-09 19:50:16.926780,Among doctor much physical interest catch.
4,alert159661,txn10059661,frequent_failure,2025-08-02 22:59:36.158113,True,2025-08-05 07:59:36.158113,Would catch themselves be represent why decade.

In [15]:
fraud_alert.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   alert_id         2000 non-null   object
 1   transaction_id   2000 non-null   object
 2   alert_type       2000 non-null   object
 3   alert_date       2000 non-null   object
 4   resolved         2000 non-null   bool
 5   resolution_date  1752 non-null   object
 6   remarks          2000 non-null   object
dtypes: bool(1), object(6)
memory usage: 95.8+ KB

In [16]:
fraud_alert['alert_date'] =pd.to_datetime( fraud_alert['alert_date'])

In [17]:
fraud_alert.isnull().sum()

alert_id             0
transaction_id       0
alert_type           0
alert_date           0
resolved             0
resolution_date    248
remarks              0
dtype: int64

In [18]:
fraud_alert['resolution_date'] = pd.to_datetime(fraud_alert['resolution_date'])

In [19]:
merchant.head()

,merchant_id,merchant_name,merchant_type,region,onboard_date,risk_score
0,merch1000,Anderson Inc,grocery,north,2022-01-14,0.07
1,merch1001,"Rojas, Newton and White",online,north,2021-08-20,0.29
2,merch1002,Knox-Reyes,food,west,2024-10-29,0.20
3,merch1003,"Joseph, Serrano and Gilmore",grocery,north,2023-07-22,0.14
4,merch1004,Brown-Jones,food,north,2024-01-02,0.32

In [20]:
merchant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   merchant_id    500 non-null    object
 1   merchant_name  500 non-null    object
 2   merchant_type  500 non-null    object
 3   region         500 non-null    object
 4   onboard_date   500 non-null    object
 5   risk_score     500 non-null    float64
dtypes: float64(1), object(5)
memory usage: 23.6+ KB

In [21]:
merchant['onboard_date'] = pd.to_datetime(merchant['onboard_date'])

In [22]:
account_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   upi_id        12000 non-null  object
 1   customer_id   12000 non-null  object
 2   bank_name     12000 non-null  object
 3   account_type  12000 non-null  object
 4   date_added    12000 non-null  object
 5   status        12000 non-null  object
dtypes: object(6)
memory usage: 562.6+ KB

In [23]:
account_details.head()

,upi_id,customer_id,bank_name,account_type,date_added,status
0,elizabeth4408@upi,cust106759,sbi,current,2022-02-22,active
1,daniel5127@upi,cust104765,hdfc,savings,2022-04-02,active
2,heidi2675@upi,cust102710,axis,savings,2023-12-19,active
3,dr.3519@upi,cust107076,axis,credit_card_linked,2025-01-23,active
4,jeremy9552@upi,cust102202,sbi,current,2025-07-18,active

In [24]:
account_details['date_added'] = pd.to_datetime(account_details['date_added'])

In [25]:
transaction_history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    100000 non-null  object
 1   upi_id            100000 non-null  object
 2   customer_id       100000 non-null  object
 3   timestamp         100000 non-null  object
 4   amount            100000 non-null  float64
 5   transaction_type  100000 non-null  object
 6   merchant_id       30149 non-null   object
 7   counterparty_upi  100000 non-null  object
 8   status            100000 non-null  object
 9   device_id         100000 non-null  object
 10  device_type       100000 non-null  object
 11  channel           100000 non-null  object
 12  fraud_flag        100000 non-null  bool
 13  reversal_flag     100000 non-null  bool
 14  failure_reason    5871 non-null    object
dtypes: bool(2), float64(1), object(12)
memory usage: 10.1+ MB

In [26]:
transaction_history.head()

,transaction_id,upi_id,customer_id,timestamp,amount,transaction_type,merchant_id,counterparty_upi,status,device_id,device_type,channel,fraud_flag,reversal_flag,failure_reason
0,txn10000000,marisa9078@upi,cust101488,2025-06-04 21:36:19.632258,9.88,send,NaN,user6545@upi,success,dev101488,feature_phone,app,False,False,NaN
1,txn10000001,michelle5950@upi,cust107876,2025-05-22 04:26:44.200117,76.25,receive,NaN,user3199@upi,success,dev107876,ios,app,False,False,NaN
2,txn10000002,jeffery4732@upi,cust100901,2025-08-02 02:34:14.690327,26.44,merchant_payment,merch1113,user4690@upi,success,dev100901,android,intent,False,False,NaN
3,txn10000003,troy1833@upi,cust105890,2025-01-30 03:53:31.110447,84.43,send,NaN,user1982@upi,success,dev105890,tablet,qr_code,False,False,NaN
4,txn10000004,tammy4986@upi,cust106780,2025-07-05 21:36:52.813878,10.33,receive,NaN,user4914@upi,success,dev106780,tablet,qr_code,False,False,NaN

In [27]:
transaction_history['timestamp'] = pd.to_datetime(transaction_history['timestamp'])

In [28]:
transaction_history.isnull().sum()

transaction_id          0
upi_id                  0
customer_id             0
timestamp               0
amount                  0
transaction_type        0
merchant_id         69851
counterparty_upi        0
status                  0
device_id               0
device_type             0
channel                 0
fraud_flag              0
reversal_flag           0
failure_reason      94129
dtype: int64

In [29]:
transaction_history['status'].value_counts()

status
success    92140
failed      5871
pending     1989
Name: count, dtype: int64

In [30]:
transaction_history[transaction_history['failure_reason'].notna()]['status'].value_counts()

status
failed    5871
Name: count, dtype: int64

In [31]:
fraud_alert[fraud_alert['resolution_date'].isna()]['resolved'].value_counts()

resolved
False    248
Name: count, dtype: int64

In [32]:
transaction_history.groupby('transaction_type')['merchant_id'].apply(lambda x: x.isnull().sum())

transaction_type
bill_pay                0
merchant_payment        0
receive             34819
send                35032
Name: merchant_id, dtype: int64

In [33]:
print(fraud_alert['resolution_date'].dtype)
print(fraud_alert['resolution_date'].head(10))

datetime64[ns]
0                          NaT
1   2024-10-11 02:41:15.203880
2   2025-02-24 10:23:55.939700
3   2025-07-09 19:50:16.926780
4   2025-08-05 07:59:36.158113
5   2025-03-06 20:01:59.435642
6   2025-08-06 08:06:42.015035
7   2021-12-19 18:00:55.193482
8                          NaT
9                          NaT
Name: resolution_date, dtype: datetime64[ns]

In [34]:
print(fraud_alert['alert_type'].str.len().max())
print(fraud_alert['remarks'].str.len().max())
print(fraud_alert['alert_id'].str.len().max())
print(fraud_alert['transaction_id'].str.len().max())

16
66
11
11

In [35]:
for col in fraud_alert.select_dtypes(include='object').columns:
    print(f"{col:20} | max_len: {fraud_alert[col].str.len().max()}")

alert_id             | max_len: 11
transaction_id       | max_len: 11
alert_type           | max_len: 16
remarks              | max_len: 66